import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import LoginScreen from "@/components/LoginScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>


      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <LoginScreen />
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn></body>
      </html>
    </ClerkProvider>
  );
}
