import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import LoginScreen from "@/components/LoginScreen";
import { DiscordContextProvider } from "@/context/DiscordContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <DiscordContextProvider>
            <div className={inter.className}>
              <SignedOut>
                <LoginScreen />
              </SignedOut>
              <SignedIn>
                {children}
              </SignedIn>
            </div>
          </DiscordContextProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
